[tool.cx_Freeze.bdsist.msi]
target_name = "CabonCheck"
target_version = "0.0.3"
initial_target_dir = "C:\\CarbonCheck"
add_to_path = false

[tool.cx_Freeze.app]
name = "CarbonCheck"
description = "Passive House Model Baseliner and Reporting."
copyright = "Copyright (C) 2023 Passive House Accelerator"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::UserWarning",
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]

[tool.coverage.run]
# --- For testing...
command_line = "-m pytest . tests"
source = ["NBDM"]
# ---
branch = true
cover_pylib = false
omit = ["*.venv/*"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.coverage.html]
directory = "_coverage_html"

[tool.black]
line-length = 90

[tool.isort]
# make it compatible with black
profile = "black" 