# Form implementation generated from reading ui file './CC_GUI/views/ui_files/layout_bldg_components.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 790)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_view_bldg_component_info = QtWidgets.QTreeView(parent=self.frame)
        self.tree_view_bldg_component_info.setUniformRowHeights(False)
        self.tree_view_bldg_component_info.setHeaderHidden(True)
        self.tree_view_bldg_component_info.setObjectName("tree_view_bldg_component_info")
        self.verticalLayout.addWidget(self.tree_view_bldg_component_info)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_bldg_component_info = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_add_bldg_component_info.setObjectName("btn_add_bldg_component_info")
        self.horizontalLayout_2.addWidget(self.btn_add_bldg_component_info)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout.addWidget(self.btn_Cancel)
        self.btn_OK = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_OK.setObjectName("btn_OK")
        self.horizontalLayout.addWidget(self.btn_OK)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Building Components"))
        self.btn_add_bldg_component_info.setText(_translate("Form", "Import Component Data from PH Model..."))
        self.btn_Cancel.setText(_translate("Form", "Cancel"))
        self.btn_OK.setText(_translate("Form", "OK"))
