baseURL = "https://ph-tools.github.io/CarbonCheck/"
title = "PH-Tools.CarbonCheck"
theme = "ph_tools"

[Params]
  author = "PH-Tools + Passive House Accelerator"
  copyright = "bldgtyp, llc"
  contact = "CarbonCheck@PassiveHouseAccelerator.com"
  ph_tools_home_url = "http://www.passivehousetools.com/"
  github_url = "https://github.com/PH-Tools/CarbonCheck"
  youtube_url = "https://www.youtube.com/channel/UCADxgnNCFNZ3uhaSvezReQA/playlists"
  package_name = "CarbonCheck"
  gh_pages_name = "CarbonCheck"
  installer_download_url = "https://github.com/PH-Tools/honeybee_grasshopper_ph/raw/main/hbph_installer.gh"
  youtube_SF_souce_files = "https://github.com/PH-Tools/honeybee_grasshopper_ph/raw/main/docs/static/downloads/Single_Family_Home_Source_Files.zip"

[menu]
  [[menu.main]]
    identifier = "quick_start"
    name = "Quick Start"
    url = "/quick_start"

  [[menu.main]]
    identifier = "learn_more"
    name = "Learn More"
    url = "/learn_more"

  [[menu.main]]
    identifier = "contact"
    name = "Contact & Help"
    url = "/contact"