name: Build Windows MSI

on:
  pull_request:
    types: [closed]
    branches:
      - main

  # push:
  #   branches:
  #     - main

  # Allows this workflow to be run manually from the 'Actions' tab in GitHub
  workflow_dispatch:

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # -- Install Develpment / Pacakaging dependencies, use cache if available
      - name: Cache python dependencies [Dev]
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies [Dev]
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      # -- Install Application dependencies, use cache if available
      - name: Cache python dependencies [App]
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies [App]
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -- Run all Tests
      - name: Run all Tests
        run: python -m pytest tests/

      # -- Build the Windows .MSI installer file using cx_Freeze
      - name: Build MSI file
        run: |
          python build_windows.py bdist_msi

      # -- Get the .MSI file from the ./dist/. folder
      # -- Commit the newly created .MSI file back to the repo
      # -- 
      # -- Github settings / Actions / General / Workflow permissions -->
      # -- "Read and write permissions"
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin main
          git add dist\*.msi
          git commit -m "Add new .MSI file"
          git push origin HEAD:main
